# Generated by Django 3.2.3 on 2021-05-16 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(choices=[('Група A', 'Група A'), ('Група B', 'Група B'), ('Група C', 'Група C'), ('Група D', 'Група D'), ('Група E', 'Група E'), ('Група F', 'Група F'), ('Група G', 'Група G'), ('Група H', 'Група H')], max_length=10)),
                ('iso_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EventDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('match_date', models.DateField()),
                ('match_start_time', models.TimeField()),
                ('match_start_time_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('score_home', models.IntegerField(default=0)),
                ('score_guest', models.IntegerField(default=0)),
                ('score_after_penalties_home', models.IntegerField(default=0)),
                ('score_after_penalties_guest', models.IntegerField(default=0)),
                ('match_state', models.CharField(blank=True, choices=[('home', 'Победа домакин'), ('guest', 'Победа гост'), ('penalties_home', 'Победа за домакин след дузпи'), ('penalties_guest', 'Победа за гост след дузпи')], max_length=20)),
                ('penalties', models.BooleanField(default=False)),
                ('phase', models.CharField(choices=[('group_phase', 'Групова фаза'), ('eighth-finals', 'Осминафинали'), ('quarterfinals', 'Четвъртфинал'), ('semifinals', 'Полуфинал'), ('little_final', 'Малък финал'), ('final', 'Финал')], max_length=20)),
                ('match_is_over', models.BooleanField(default=False)),
                ('country_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_guest', to='matches.countries')),
                ('country_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_home', to='matches.countries')),
            ],
            options={
                'unique_together': {('country_home', 'country_guest', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, null=True)),
                ('bonus_points_added', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_match_state', models.CharField(choices=[('home', 'Победа домакин'), ('guest', 'Победа гост'), ('penalties_home', 'Победа за домакин след дузпи'), ('penalties_guest', 'Победа за гост след дузпи')], max_length=20)),
                ('prediction_goals_home', models.IntegerField(default=0, null=True)),
                ('prediction_goals_guest', models.IntegerField(default=0, null=True)),
                ('gave_prediction', models.BooleanField(default=False)),
                ('prediction_note', models.TextField(default='Дал си прогноза за мача: 1 т.')),
                ('points_gained', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_edit', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_predictions', to='matches.matches')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
