# Generated by Django 3.2.3 on 2021-05-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventgroups_unique_together'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['match_number']},
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='country_guest',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='country_home',
            new_name='home',
        ),
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together={('home', 'guest', 'phase')},
        ),
    ]
