# Generated by Django 3.2.12 on 2022-04-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_start_time']},
        ),
    ]
