# Generated by Django 3.2.3 on 2021-05-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20210517_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='match_is_over',
            field=models.BooleanField(default=False),
        ),
    ]
