# Generated by Django 3.2.12 on 2022-04-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-group__event_group', 'name')},
        ),
    ]
