# Generated by Django 3.2.3 on 2021-05-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventphases',
            unique_together={('event', 'phase')},
        ),
    ]
