# Generated by Django 3.2.3 on 2021-05-16 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventphases_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmatchstates',
            unique_together={('event', 'match_state')},
        ),
        migrations.AlterUniqueTogether(
            name='teams',
            unique_together={('group', 'name')},
        ),
        migrations.RemoveField(
            model_name='teams',
            name='short_name',
        ),
    ]
