# Generated by Django 3.2.3 on 2021-05-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventgroups_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug_name',
            field=models.SlugField(default='example', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=60),
        ),
    ]
