# Generated by Django 3.2.3 on 2021-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210517_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug_name',
            field=models.SlugField(max_length=180, unique=True),
        ),
    ]
