# Generated by Django 3.2.3 on 2021-05-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_top_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='eventmatchstates',
            name='match_state',
            field=models.CharField(choices=[('home', 'Победа домакин'), ('guest', 'Победа гост'), ('tie', 'Равен'), ('penalties_home', 'Победа за домакин след дузпи'), ('penalties_guest', 'Победа за гост след дузпи')], max_length=20),
        ),
    ]
