# Generated by Django 3.2.3 on 2021-05-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210517_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphases',
            name='phase_match_states',
            field=models.ManyToManyField(to='events.EventMatchStates'),
        ),
    ]
