# Generated by Django 3.2.3 on 2021-05-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventphases_phase_match_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphases',
            name='phase_match_states',
            field=models.ManyToManyField(limit_choices_to=models.Q(('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_phases', to='events.event'))), to='events.EventMatchStates'),
        ),
    ]
