# Generated by Django 3.2.3 on 2021-05-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventphases_phase_match_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphases',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
