version: "3.8"

services:
  web:
    command: /docker/run-server.sh local
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: friendly-bet/django:4.2
    container_name: friendly-bet.django
    env_file: ./docker/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    links:
      - db


  python-black:
    image: pyfound/black:latest
    container_name: myhealth.python-black
    command: blackd --bind-host 0.0.0.0 --bind-port 45484
    ports:
      - "45484:45484"

  db:
    image: mysql:8.0
    container_name: myhealth.db
    command: --default-authentication-plugin=mysql_native_password
      --slow-query-log=ON
      --long-query-time=1
      --min-examined-row-limit=5000
      --log_queries_not_using_indexes=ON
      --slow-query-log-file=/var/lib/mysql/#debug_log_slow_queries.log
    env_file: ./docker/.env
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
