# Generated by Django 3.2.3 on 2021-05-16 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_name', models.CharField(max_length=200)),
                ('active_until', models.DateTimeField()),
                ('correct_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('points', models.IntegerField()),
                ('participate_link', models.BooleanField(default=False)),
                ('bonus_active', models.BooleanField(default=False)),
                ('input_filed', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('all-countries', 'all-countries'), ('choices', 'choices')], default='text', max_length=20)),
                ('archived', models.BooleanField(default=False)),
                ('available_choices', models.CharField(default='No', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='UserBonusSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bonus_points', models.IntegerField()),
                ('total_summary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BonusUserPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prediction', models.CharField(max_length=500)),
                ('points_gained', models.IntegerField(default=0)),
                ('summary_text', models.CharField(max_length=500)),
                ('user_participate', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_user', to=settings.AUTH_USER_MODEL)),
                ('user_bonus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonus_name', to='bonus_points.bonusdescription')),
            ],
        ),
        migrations.CreateModel(
            name='BonusUserAutoPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_gained', models.IntegerField(default=0)),
                ('summary_text', models.CharField(max_length=500)),
                ('auto_user_bonus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_user_bonus_name', to='bonus_points.bonusdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bonus_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
