# Generated by Django 3.2.3 on 2021-05-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_points', '0002_auto_20210522_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusdescription',
            name='available_choices',
            field=models.CharField(blank=True, help_text='CSV of available choices', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='bonusdescription',
            name='bonus_input',
            field=models.CharField(choices=[('number', 'Number'), ('teams', 'All Event Teams'), ('choices', 'Defined choices in available_choices field')], default='text', max_length=20),
        ),
    ]
