# Generated by Django 3.2.3 on 2021-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_points', '0003_auto_20210523_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusdescription',
            name='auto_bonus_calculator_function_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
