# Generated by Django 3.2.3 on 2021-05-27 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonus_points', '0004_bonusdescription_auto_bonus_calculator_function_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBonusUserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_gained', models.IntegerField(default=0)),
                ('summary_text', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bonus_obj', to='bonus_points.bonusdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_bonus_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
