# Generated by Django 3.2.3 on 2021-07-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_points', '0005_autobonususerscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbonussummary',
            name='total_bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbonussummary',
            name='total_summary',
            field=models.TextField(blank=True),
        ),
    ]
