# Generated by Django 3.2.3 on 2021-07-08 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_event_total_matches'),
        ('bonus_points', '0006_auto_20210708_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbonussummary',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_bonus', to='events.event'),
        ),
    ]
